# .coderabbit.yaml
reviews:
  summarize: true
  review_simple_changes: false
  path_filters:
    - "!**/*.md"
    - "!**/*.txt"
    - "!**/package-lock.json"
  auto_approve:
    enabled: false
chat:
  enabled: true
language: korean